import { BadRequestException,ForbiddenException,Injectable,NotFoundException } from '@nestjs/common';
import { User,UserRole } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class MaterialsService {constructor(private prisma:PrismaService){}private db(){return this.prisma as any}private lecturer(u:User){if(u.role!==UserRole.LECTURER)throw new ForbiddenException('Lecturer access required')}private rec(v:unknown){if(!v||typeof v!=='object'||Array.isArray(v))throw new BadRequestException('Request body must be an object');return v as Record<string,any>}private text(v:any,n:string){if(typeof v!=='string'||!v.trim())throw new BadRequestException(`${n} is required`);return v.trim()}private files(v:any){if(!Array.isArray(v)||!v.length)throw new BadRequestException('Upload at least one file');return v.map(x=>{const f=this.rec(x);return{name:this.text(f.name,'file.name'),uri:this.text(f.uri,'file.uri'),type:typeof f.type==='string'?f.type:null,size:typeof f.size==='number'?f.size:null}})}
private include(studentId?:string){return{courseOffering:{include:{course:true,academicSession:true,conversation:{include:{members:{include:{user:true}}}}}},lecturer:true,accesses:studentId?{where:{studentId}}:true,_count:{select:{accesses:true}}}}
async offerings(u:User){this.lecturer(u);const rows=await this.db().courseOffering.findMany({where:{lecturerId:u.id,status:'ACTIVE'},include:{course:true,academicSession:true}});return rows.map((o:any)=>({id:o.id,courseCode:o.course.code,courseName:o.course.name,academicYear:o.academicSession.academicYear,semester:o.academicSession.semester}))}
async list(u:User){const where=u.role===UserRole.LECTURER?{lecturerId:u.id}:u.role===UserRole.STUDENT?{status:'PUBLISHED',courseOffering:{conversation:{members:{some:{userId:u.id}}}}}:{};const rows=await this.db().courseMaterial.findMany({where,include:this.include(u.role===UserRole.STUDENT?u.id:undefined),orderBy:[{pinned:'desc'},{publishedAt:'desc'},{createdAt:'desc'}]});return rows.map((x:any)=>this.response(x,u))}
async create(u:User,body:unknown){this.lecturer(u);const b=this.rec(body);const offering=await this.db().courseOffering.findFirst({where:{id:this.text(b.courseOfferingId,'courseOfferingId'),lecturerId:u.id,status:'ACTIVE'}});if(!offering)throw new ForbiddenException('Course offering unavailable');const type=this.text(b.type,'type').toUpperCase();if(!['NOTES','SLIDES','READING','REFERENCE','REVISION'].includes(type))throw new BadRequestException('Invalid material type');const publish=b.publish===true;const row=await this.db().courseMaterial.create({data:{courseOfferingId:offering.id,lecturerId:u.id,title:this.text(b.title,'title'),description:typeof b.description==='string'&&b.description.trim()?b.description.trim():null,type,topic:typeof b.topic==='string'&&b.topic.trim()?b.topic.trim():null,files:this.files(b.files),allowDownload:b.allowDownload!==false,pinned:b.pinned===true,status:publish?'PUBLISHED':'DRAFT',publishedAt:publish?new Date():null},include:this.include()});if(publish)await this.notify(row);return this.response(row,u)}
async detail(u:User,id:string){const row=await this.db().courseMaterial.findUnique({where:{id},include:this.include(u.role===UserRole.STUDENT?u.id:undefined)});if(!row)throw new NotFoundException('Material not found');await this.canView(u,row);return this.response(row,u)}
async update(u:User,id:string,body:unknown){this.lecturer(u);const b=this.rec(body);const current=await this.db().courseMaterial.findUnique({where:{id}});if(!current)throw new NotFoundException('Material not found');if(current.lecturerId!==u.id)throw new ForbiddenException('Material belongs to another lecturer');const status=b.status?this.text(b.status,'status').toUpperCase():current.status;if(!['DRAFT','PUBLISHED','ARCHIVED'].includes(status))throw new BadRequestException('Invalid status');const nextFiles=b.files!==undefined?this.files(b.files):undefined;const changed=nextFiles&&JSON.stringify(nextFiles)!==JSON.stringify(current.files);const row=await this.db().courseMaterial.update({where:{id},data:{...(b.title!==undefined?{title:this.text(b.title,'title')}:{}),...(b.description!==undefined?{description:typeof b.description==='string'&&b.description.trim()?b.description.trim():null}:{}),...(b.topic!==undefined?{topic:typeof b.topic==='string'&&b.topic.trim()?b.topic.trim():null}:{}),...(b.type!==undefined?{type:this.text(b.type,'type').toUpperCase()}:{}),...(nextFiles?{files:nextFiles}:{}),...(changed?{version:{increment:1}}:{}),...(b.allowDownload!==undefined?{allowDownload:b.allowDownload!==false}:{}),...(b.pinned!==undefined?{pinned:b.pinned===true}:{}),status,...(status==='PUBLISHED'&&!current.publishedAt?{publishedAt:new Date()}: {})},include:this.include()});if(current.status==='DRAFT'&&status==='PUBLISHED')await this.notify(row);return this.response(row,u)}
async remove(u:User,id:string){this.lecturer(u);const row=await this.db().courseMaterial.findUnique({where:{id},include:{accesses:{where:{firstOpenedAt:{not:null}}}}});if(!row)throw new NotFoundException('Material not found');if(row.lecturerId!==u.id)throw new ForbiddenException('Material belongs to another lecturer');if(row.accesses.length)throw new BadRequestException('Opened materials cannot be deleted. Archive it instead.');await this.db().courseMaterial.delete({where:{id}});return{deleted:true,id}}
async open(u:User,id:string){if(u.role!==UserRole.STUDENT)throw new ForbiddenException('Student access required');const row=await this.db().courseMaterial.findUnique({where:{id},include:this.include(u.id)});if(!row)throw new NotFoundException('Material not found');await this.canView(u,row);const now=new Date();await this.db().courseMaterialAccess.upsert({where:{materialId_studentId:{materialId:id,studentId:u.id}},create:{materialId:id,studentId:u.id,firstOpenedAt:now,lastOpenedAt:now},update:{firstOpenedAt:row.accesses[0]?.firstOpenedAt??now,lastOpenedAt:now}});return{opened:true}}
async dismiss(u:User,id:string){if(u.role!==UserRole.STUDENT)throw new ForbiddenException('Student access required');const row=await this.db().courseMaterial.findUnique({where:{id},include:this.include(u.id)});if(!row)throw new NotFoundException('Material not found');await this.canView(u,row);await this.db().courseMaterialAccess.upsert({where:{materialId_studentId:{materialId:id,studentId:u.id}},create:{materialId:id,studentId:u.id,alertDismissedAt:new Date()},update:{alertDismissedAt:new Date()}});return{dismissed:true}}
private async canView(u:User,row:any){if(u.role===UserRole.ADMIN||row.lecturerId===u.id)return;const member=row.courseOffering.conversation?.members?.some((m:any)=>m.userId===u.id);if(u.role!==UserRole.STUDENT||row.status!=='PUBLISHED'||!member)throw new ForbiddenException('You cannot access this material')}
private response(x:any,u:User){const access=u.role===UserRole.STUDENT?x.accesses?.[0]:null;return{id:x.id,title:x.title,description:x.description,type:x.type.toLowerCase(),topic:x.topic,files:x.files,version:x.version,allowDownload:x.allowDownload,pinned:x.pinned,status:x.status.toLowerCase(),publishedAt:x.publishedAt?.toISOString()??null,createdAt:x.createdAt.toISOString(),course:{offeringId:x.courseOffering.id,conversationId:x.courseOffering.conversationId,code:x.courseOffering.course.code,name:x.courseOffering.course.name},lecturer:{id:x.lecturer.id,name:x.lecturer.name},viewCount:(x.accesses??[]).filter((a:any)=>a.firstOpenedAt).length,isNew:!access?.firstOpenedAt,alertDismissed:Boolean(access?.alertDismissedAt)}}
private async notify(x:any){const ids=(x.courseOffering.conversation?.members??[]).filter((m:any)=>m.user.role===UserRole.STUDENT).map((m:any)=>m.user.id);if(ids.length)await this.db().notification.createMany({data:ids.map((userId:string)=>({userId,type:'material_published',title:'New course material',body:`${x.courseOffering.course.code}: ${x.title}`,data:{materialId:x.id,conversationId:x.courseOffering.conversationId}}))})}}
