import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { User, UserRole } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable()
export class AnnouncementsService {
  constructor(private prisma: PrismaService) {}
  private db() { return this.prisma as any; }
  private lecturer(u: User) { if (u.role !== UserRole.LECTURER) throw new ForbiddenException('Lecturer access required'); }
  private object(v: unknown) { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new BadRequestException('Request body must be an object'); return v as Record<string, any>; }
  private required(v: any, field: string) { if (typeof v !== 'string' || !v.trim()) throw new BadRequestException(`${field} is required`); return v.trim(); }
  private attachments(v: any) { if (!Array.isArray(v)) throw new BadRequestException('attachments must be an array'); return v.map((entry) => { const f = this.object(entry); return { name: this.required(f.name, 'file.name'), uri: this.required(f.uri, 'file.uri'), type: typeof f.type === 'string' ? f.type : null, size: typeof f.size === 'number' ? f.size : null }; }); }
  private include(studentId?: string) { return { courseOffering: { include: { course: true, academicSession: true, conversation: { include: { members: { include: { user: true } } } } } }, lecturer: true, accesses: studentId ? { where: { studentId } } : true }; }
  async offerings(u: User) { this.lecturer(u); const rows = await this.db().courseOffering.findMany({ where: { lecturerId: u.id, status: 'ACTIVE' }, include: { course: true, academicSession: true } }); return rows.map((x: any) => ({ id: x.id, courseCode: x.course.code, courseName: x.course.name, academicYear: x.academicSession.academicYear, semester: x.academicSession.semester })); }
  async list(u: User) { const where = u.role === UserRole.LECTURER ? { lecturerId: u.id } : u.role === UserRole.STUDENT ? { status: { in: ['PUBLISHED', 'ARCHIVED'] }, courseOffering: { conversation: { members: { some: { userId: u.id } } } } } : {}; const rows = await this.db().courseAnnouncement.findMany({ where, include: this.include(u.role === UserRole.STUDENT ? u.id : undefined), orderBy: [{ pinned: 'desc' }, { publishedAt: 'desc' }, { createdAt: 'desc' }] }); return rows.map((x: any) => this.response(x, u)); }
  async create(u: User, input: unknown) { this.lecturer(u); const b = this.object(input); const offering = await this.db().courseOffering.findFirst({ where: { id: this.required(b.courseOfferingId, 'courseOfferingId'), lecturerId: u.id, status: 'ACTIVE' } }); if (!offering) throw new ForbiddenException('Course offering unavailable'); const priority = String(b.priority ?? 'NORMAL').toUpperCase(); if (!['NORMAL', 'IMPORTANT', 'URGENT'].includes(priority)) throw new BadRequestException('Invalid priority'); const publish = b.publish === true; const row = await this.db().courseAnnouncement.create({ data: { courseOfferingId: offering.id, lecturerId: u.id, title: this.required(b.title, 'title'), body: this.required(b.body, 'body'), priority, attachments: this.attachments(b.attachments ?? []), pinned: b.pinned === true, status: publish ? 'PUBLISHED' : 'DRAFT', publishedAt: publish ? new Date() : null }, include: this.include() }); if (publish) await this.notify(row); return this.response(row, u); }
  async detail(u: User, id: string) { const row = await this.db().courseAnnouncement.findUnique({ where: { id }, include: this.include(u.role === UserRole.STUDENT ? u.id : undefined) }); if (!row) throw new NotFoundException('Announcement not found'); await this.canView(u, row); return this.response(row, u); }
  async update(u: User, id: string, input: unknown) { this.lecturer(u); const b = this.object(input); const current = await this.db().courseAnnouncement.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Announcement not found'); if (current.lecturerId !== u.id) throw new ForbiddenException('Announcement belongs to another lecturer'); const status = b.status ? this.required(b.status, 'status').toUpperCase() : current.status; if (!['DRAFT', 'PUBLISHED', 'ARCHIVED'].includes(status)) throw new BadRequestException('Invalid status'); const priority = b.priority ? this.required(b.priority, 'priority').toUpperCase() : current.priority; if (!['NORMAL', 'IMPORTANT', 'URGENT'].includes(priority)) throw new BadRequestException('Invalid priority'); const row = await this.db().courseAnnouncement.update({ where: { id }, data: { ...(b.title !== undefined ? { title: this.required(b.title, 'title') } : {}), ...(b.body !== undefined ? { body: this.required(b.body, 'body') } : {}), ...(b.attachments !== undefined ? { attachments: this.attachments(b.attachments) } : {}), ...(b.pinned !== undefined ? { pinned: b.pinned === true } : {}), priority, status, ...(status === 'PUBLISHED' && !current.publishedAt ? { publishedAt: new Date() } : {}) }, include: this.include() }); if (current.status === 'DRAFT' && status === 'PUBLISHED') await this.notify(row); return this.response(row, u); }
  async remove(u: User, id: string) { this.lecturer(u); const row = await this.db().courseAnnouncement.findUnique({ where: { id }, include: { accesses: { where: { readAt: { not: null } } } } }); if (!row) throw new NotFoundException('Announcement not found'); if (row.lecturerId !== u.id) throw new ForbiddenException('Announcement belongs to another lecturer'); if (row.accesses.length) throw new BadRequestException('Read announcements cannot be deleted. Archive it instead.'); await this.db().courseAnnouncement.delete({ where: { id } }); return { deleted: true, id }; }
  async read(u: User, id: string) { const row = await this.studentRow(u, id); await this.db().announcementAccess.upsert({ where: { announcementId_studentId: { announcementId: id, studentId: u.id } }, create: { announcementId: id, studentId: u.id, readAt: new Date() }, update: { readAt: row.accesses[0]?.readAt ?? new Date() } }); return { read: true }; }
  async dismiss(u: User, id: string) { await this.studentRow(u, id); await this.db().announcementAccess.upsert({ where: { announcementId_studentId: { announcementId: id, studentId: u.id } }, create: { announcementId: id, studentId: u.id, alertDismissedAt: new Date() }, update: { alertDismissedAt: new Date() } }); return { dismissed: true }; }
  private async studentRow(u: User, id: string) { if (u.role !== UserRole.STUDENT) throw new ForbiddenException('Student access required'); const row = await this.db().courseAnnouncement.findUnique({ where: { id }, include: this.include(u.id) }); if (!row) throw new NotFoundException('Announcement not found'); await this.canView(u, row); return row; }
  private async canView(u: User, row: any) { if (u.role === UserRole.ADMIN || row.lecturerId === u.id) return; const member = row.courseOffering.conversation?.members?.some((m: any) => m.userId === u.id); if (u.role !== UserRole.STUDENT || !['PUBLISHED', 'ARCHIVED'].includes(row.status) || !member) throw new ForbiddenException('You cannot access this announcement'); }
  private response(x: any, u: User) { const access = u.role === UserRole.STUDENT ? x.accesses?.[0] : null; return { id: x.id, title: x.title, body: x.body, priority: x.priority.toLowerCase(), attachments: x.attachments, pinned: x.pinned, status: x.status.toLowerCase(), publishedAt: x.publishedAt?.toISOString() ?? null, createdAt: x.createdAt.toISOString(), updatedAt: x.updatedAt.toISOString(), course: { offeringId: x.courseOffering.id, conversationId: x.courseOffering.conversationId, code: x.courseOffering.course.code, name: x.courseOffering.course.name }, lecturer: { id: x.lecturer.id, name: x.lecturer.name }, readCount: (x.accesses ?? []).filter((a: any) => a.readAt).length, isRead: Boolean(access?.readAt), alertDismissed: Boolean(access?.alertDismissedAt) }; }
  private async notify(x: any) { const ids = (x.courseOffering.conversation?.members ?? []).filter((m: any) => m.user.role === UserRole.STUDENT).map((m: any) => m.user.id); if (ids.length) await this.db().notification.createMany({ data: ids.map((userId: string) => ({ userId, type: 'announcement_published', title: x.priority === 'URGENT' ? 'Urgent course announcement' : 'New course announcement', body: `${x.courseOffering.course.code}: ${x.title}`, data: { announcementId: x.id, conversationId: x.courseOffering.conversationId } })) }); }
}
