import { useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { StatusBar } from '@/src/components/common/StatusBar';
import { ScreenHeader } from '@/src/components/common/ScreenHeader';
import { quizService } from '@/src/services/quiz.service';
import { Quiz } from '@/src/types/quiz.types';

export default function QuizDetail(){const{quizId}=useLocalSearchParams<{quizId:string}>();const[q,setQ]=useState<Quiz|null>(null);const[starting,setStarting]=useState(false);useEffect(()=>{if(quizId)quizService.detail(quizId).then(setQ).catch(e=>Alert.alert('Could not load quiz',e.message));},[quizId]);if(!q)return <SafeAreaView className="flex-1 bg-[#F5F7FA]"/>;const now=Date.now(),available=q.status==='published'&&now>=new Date(q.startAt).getTime()&&now<=new Date(q.endAt).getTime()&&q.attemptsUsed<q.maxAttempts;const start=async()=>{try{setStarting(true);await quizService.start(q.id);router.push({pathname:'/(student)/tasks/quiz-attempt',params:{quizId:q.id}} as any);}catch(e){Alert.alert('Cannot start quiz',e instanceof Error?e.message:'Please try again.');}finally{setStarting(false)}};return <SafeAreaView className="flex-1 bg-[#051839]"><StatusBar style="light" backgroundColor="#051839"/><ScreenHeader title={q.title} fallbackRoute="/(student)/tasks/quizzes"/><ScrollView className="flex-1 bg-[#F5F7FA]" contentContainerStyle={{padding:16,gap:14}}>
<View className="rounded-2xl bg-white p-4"><Text className="font-bold text-blue-600">{q.course.code} · {q.course.name}</Text><Text className="mt-4 text-sm leading-6 text-slate-700">{q.instructions}</Text><View className="mt-4 rounded-xl bg-slate-50 p-3"><Text className="text-sm text-slate-600">Questions: {q.questionCount}</Text><Text className="mt-1 text-sm text-slate-600">Duration: {q.durationMinutes} minutes</Text><Text className="mt-1 text-sm text-slate-600">Marks: {q.attempt?.score??'-'}/{q.totalMarks}</Text><Text className="mt-1 text-sm text-slate-600">Attempts: {q.attemptsUsed}/{q.maxAttempts}</Text><Text className="mt-1 text-sm text-slate-600">Closes: {new Date(q.endAt).toLocaleString()}</Text></View></View>
{q.attempt?.submittedAt?<View className="rounded-2xl bg-emerald-50 p-4"><Text className="font-extrabold text-emerald-800">Quiz submitted</Text><Text className="mt-1 text-sm text-emerald-700">{q.attempt.resultsReleased?`Released score: ${q.attempt.score}/${q.totalMarks}`:'Results have not been released yet.'}</Text></View>:null}
{q.attempt?.status==='in_progress'?<Pressable onPress={()=>router.push({pathname:'/(student)/tasks/quiz-attempt',params:{quizId:q.id}} as any)} className="items-center rounded-full bg-blue-600 py-4"><Text className="font-bold text-white">Resume Quiz</Text></Pressable>:available?<Pressable disabled={starting} onPress={()=>void start()} className="items-center rounded-full bg-blue-600 py-4"><Text className="font-bold text-white">{starting?'Starting...':'Start Quiz'}</Text></Pressable>:null}
</ScrollView></SafeAreaView>}
