export const adminUsers = [
  {
    id: 'stephen-appiah',
    initials: 'SA',
    avatarColor: 'bg-[#3B6AE3]',
    name: 'Stephen Appiah',
    meta: '0323080542 · Student · CS ·',
    identifier: '0323080542',
    role: 'Student',
    department: 'CS Dept',
    statusDot: 'bg-lime-500',
    statusText: 'Online',
    rowBg: 'bg-white',
    actions: ['👁️', '✉️', '🚫'],
    email: '[email protected]',
    joined: 'Sep 4, 2024',
    lastLogin: 'Today · Android',
    twoFactor: 'Not set',
    stats: [
      { label: 'Messages', value: '248' },
      { label: 'Courses', value: '5' },
      { label: 'Activity', value: '94%' },
    ],
  },
  {
    id: 'rudolf-gavor',
    initials: 'RG',
    avatarColor: 'bg-[#4CB37C]',
    name: 'Rudolf S. K. Gavor',
    meta: '0323080246 · Student · CS ·',
    identifier: '0323080246',
    role: 'Student',
    department: 'CS Dept',
    statusDot: 'bg-lime-500',
    statusText: 'Online',
    rowBg: 'bg-white',
    actions: ['👁️', '✉️', '🚫'],
    email: '[email protected]',
    joined: 'Sep 2, 2024',
    lastLogin: 'Today · Web',
    twoFactor: 'Enabled',
    stats: [
      { label: 'Messages', value: '193' },
      { label: 'Courses', value: '5' },
      { label: 'Activity', value: '88%' },
    ],
  },
  {
    id: 'george-agordzo',
    initials: 'GA',
    avatarColor: 'bg-[#E79B2C]',
    name: 'Mr. George Agordzo',
    meta: 'STAFF-001 · Lecturer · CS ·',
    identifier: 'STAFF-001',
    role: 'Lecturer',
    department: 'CS Dept',
    statusDot: 'bg-lime-500',
    statusText: 'Online',
    rowBg: 'bg-white',
    actions: ['👁️', '✉️', '🚫'],
    email: '[email protected]',
    joined: 'Aug 15, 2023',
    lastLogin: 'Today · iPhone',
    twoFactor: 'Enabled',
    stats: [
      { label: 'Messages', value: '82' },
      { label: 'Courses', value: '3' },
      { label: 'Activity', value: '91%' },
    ],
  },
  {
    id: 'ama-yeboah',
    initials: 'AY',
    avatarColor: 'bg-[#4294DB]',
    name: 'Ama Yeboah',
    meta: '0323080421 · Student · CS ·',
    identifier: '0323080421',
    role: 'Student',
    department: 'CS Dept',
    statusDot: 'bg-amber-500',
    statusText: 'Pending',
    rowBg: 'bg-white',
    actions: ['⏳', '✅', '✕'],
    email: '[email protected]',
    joined: 'Sep 6, 2024',
    lastLogin: 'Yesterday · Android',
    twoFactor: 'Not set',
    stats: [
      { label: 'Messages', value: '34' },
      { label: 'Courses', value: '5' },
      { label: 'Activity', value: '52%' },
    ],
  },
  {
    id: 'kofi-agyemang',
    initials: 'KA',
    avatarColor: 'bg-[#DF5147]',
    name: 'Kofi Agyemang',
    meta: '0323080310 · Student · CS ·',
    identifier: '0323080310',
    role: 'Student',
    department: 'CS Dept',
    statusDot: 'bg-red-500',
    statusText: 'Suspended',
    rowBg: 'bg-[#FFF7F7]',
    actions: ['🔴', '👁️', '✅'],
    email: '[email protected]',
    joined: 'Sep 1, 2024',
    lastLogin: '3 days ago · Web',
    twoFactor: 'Not set',
    stats: [
      { label: 'Messages', value: '11' },
      { label: 'Courses', value: '5' },
      { label: 'Activity', value: '18%' },
    ],
  },
] as const;

export function getAdminUserById(id?: string | string[]) {
  if (!id) return null;
  const value = Array.isArray(id) ? id[0] : id;
  return adminUsers.find((user) => user.id === value) ?? null;
}
